// ============================================================
// data.js — 팀, 선수, 아이콘 데이터 원본
// ============================================================

const allTeams = {
    "바르셀로나": {
        displayName: "바르셀로나", city: "바르셀로나", logoCode: "FCB", league: 1, budget: 800,
        players: [
            { name: "페드리", position: "MF", country: "스페인", age: 22, rating: 89 },
            { name: "로베르트 레반도프스키", position: "FW", country: "폴란드", age: 36, rating: 90 },
            { name: "라민 야말", position: "FW", country: "스페인", age: 18, rating: 89 },
            { name: "하피냐", position: "FW", country: "브라질", age: 28, rating: 93 },
            { name: "이냐키 페냐", position: "GK", country: "스페인", age: 26, rating: 73 },
            { name: "마커스 래시포드", position: "MF", country: "잉글랜드", age: 27, rating: 80 },
            { name: "마르크 안드레 테어 슈테겐", position: "GK", country: "독일", age: 33, rating: 79 },
            { name: "안드레아스 크리스텐센", position: "DF", country: "덴마크", age: 29, rating: 78 },
            { name: "가비", position: "MF", country: "스페인", age: 20, rating: 84 },
            { name: "페르민 로페스", position: "MF", country: "스페인", age: 22, rating: 82 },
            { name: "프렝키 더용", position: "MF", country: "네덜란드", age: 28, rating: 86 },
            { name: "쥘 쿤데", position: "DF", country: "프랑스", age: 26, rating: 88 },
            { name: "보이치에흐 슈체스니", position: "GK", country: "폴란드", age: 35, rating: 83 },
            { name: "파우 쿠바르시", position: "DF", country: "스페인", age: 18, rating: 84 },
            { name: "알레한드로 발데", position: "DF", country: "스페인", age: 22, rating: 83 },
            { name: "다니 올모", position: "MF", country: "스페인", age: 27, rating: 83 },
        ],
        description: "꿈과 열정이 살아 숨쉬는 카탈루냐의 자존심"
    },
    "레알_마드리드": {
        displayName: "레알 마드리드", city: "마드리드", logoCode: "RMA", league: 1, budget: 1500,
        players: [
            { name: "티보 쿠르투아", position: "GK", country: "벨기에", age: 33, rating: 89 },
            { name: "주드 벨링엄", position: "MF", country: "잉글랜드", age: 22, rating: 89 },
            { name: "에두아르도 카마빙가", position: "MF", country: "프랑스", age: 22, rating: 85 },
            { name: "비니시우스 주니오르", position: "FW", country: "브라질", age: 25, rating: 93 },
            { name: "페데리코 발베르데", position: "MF", country: "우루과이", age: 27, rating: 92 },
            { name: "킬리안 음바페", position: "FW", country: "프랑스", age: 26, rating: 95 },
            { name: "호드리구", position: "FW", country: "브라질", age: 24, rating: 89 },
            { name: "트렌트 알렉산더아놀드", position: "DF", country: "잉글랜드", age: 26, rating: 86 },
            { name: "오렐리앙 추아메니", position: "MF", country: "프랑스", age: 25, rating: 85 },
            { name: "에데르 밀리탕", position: "DF", country: "브라질", age: 27, rating: 86 },
            { name: "안토니오 뤼디거", position: "DF", country: "독일", age: 32, rating: 82 },
            { name: "딘 하위선", position: "DF", country: "스페인", age: 20, rating: 86 },
        ],
        description: "황실의 위엄을 지닌 세계 최고의 클럽"
    },
    "맨체스터_시티": {
        displayName: "맨체스터 시티", city: "맨체스터", logoCode: "MCI", league: 1, budget: 2200,
        players: [
            { name: "엘링 홀란드", position: "FW", country: "노르웨이", age: 25, rating: 94 },
            { name: "로드리", position: "MF", country: "스페인", age: 29, rating: 93 },
            { name: "요슈코 그바르디올", position: "DF", country: "크로아티아", age: 23, rating: 89 },
            { name: "라얀 셰르키", position: "MF", country: "프랑스", age: 21, rating: 89 },
            { name: "잔루이지 돈나룸마", position: "GK", country: "이탈리아", age: 26, rating: 87 },
            { name: "후벵 디아스", position: "DF", country: "포르투갈", age: 28, rating: 87 },
            { name: "제레미 도쿠", position: "FW", country: "벨기에", age: 23, rating: 88 },
            { name: "마크 게히", position: "DF", country: "잉글랜드", age: 25, rating: 85 },
            { name: "티자니 라인더르스", position: "MF", country: "네덜란드", age: 27, rating: 85 },
            { name: "라얀 아이트누리", position: "DF", country: "알제리", age: 24, rating: 85 },
            { name: "베르나르두 실바", position: "MF", country: "포르투갈", age: 30, rating: 84 },
            { name: "필 포든", position: "FW", country: "잉글랜드", age: 25, rating: 84 },
        ],
        description: "천상의 축구를 구현하는 맨체스터의 블루 문"
    },
    "맨체스터_유나이티드": {
        displayName: "맨체스터 유나이티드", city: "맨체스터", logoCode: "MUN", league: 2, budget: 1500,
        players: [
            { name: "브루노 페르난데스", position: "MF", country: "포르투갈", age: 30, rating: 89 },
            { name: "마테우스 쿠냐", position: "FW", country: "브라질", age: 26, rating: 88 },
            { name: "브라이언 음뵈모", position: "FW", country: "카메룬", age: 25, rating: 87 },
            { name: "카세미루", position: "MF", country: "브라질", age: 33, rating: 85 },
            { name: "센느 라멘스", position: "GK", country: "벨기에", age: 23, rating: 85 },
            { name: "아마드 디알로", position: "MF", country: "코트디부아르", age: 23, rating: 84 },
            { name: "누사이르 마즈라위", position: "DF", country: "모로코", age: 27, rating: 84 },
            { name: "리산드로 마르티네스", position: "DF", country: "아르헨티나", age: 27, rating: 84 },
            { name: "베냐민 셰슈코", position: "FW", country: "슬로베니아", age: 22, rating: 84 },
            { name: "마누엘 우가르테", position: "MF", country: "우루과이", age: 24, rating: 83 },
            { name: "마테이스 더리흐트", position: "DF", country: "네덜란드", age: 25, rating: 82 },
            { name: "메이슨 마운트", position: "MF", country: "잉글랜드", age: 26, rating: 82 },
        ],
        description: "붉은 악마들의 자존심과 전통"
    },
    "리버풀": {
        displayName: "리버풀", city: "리버풀", logoCode: "LIV", league: 1, budget: 1200,
        players: [
            { name: "버질 반 다이크", position: "DF", country: "네덜란드", age: 34, rating: 92 },
            { name: "모하메드 살라", position: "FW", country: "이집트", age: 33, rating: 89 },
            { name: "도미니크 소보슬러이", position: "MF", country: "헝가리", age: 24, rating: 89 },
            { name: "라이언 흐라벤베르흐", position: "MF", country: "네덜란드", age: 23, rating: 88 },
            { name: "알렉시스 맥 알리스터", position: "MF", country: "아르헨티나", age: 26, rating: 87 },
            { name: "알리송", position: "GK", country: "브라질", age: 32, rating: 86 },
            { name: "위고 에키티케", position: "FW", country: "프랑스", age: 23, rating: 86 },
            { name: "제레미 프림퐁", position: "DF", country: "네덜란드", age: 24, rating: 85 },
            { name: "알렉산데르 이사크", position: "FW", country: "스웨덴", age: 25, rating: 85 },
            { name: "플로리안 비르츠", position: "FW", country: "독일", age: 22, rating: 85 },
            { name: "이브라히마 코나테", position: "DF", country: "프랑스", age: 26, rating: 84 },
            { name: "앤드류 로버트슨", position: "DF", country: "스코틀랜드", age: 31, rating: 83 },
        ],
        description: "You'll Never Walk Alone - 리버풀의 불굴의 정신"
    },
    "토트넘_홋스퍼": {
        displayName: "토트넘 홋스퍼", city: "런던", logoCode: "TOT", league: 1, budget: 1000,
        players: [
            { name: "손흥민", position: "FW", country: "대한민국", age: 33, rating: 93 },
            { name: "크리스티안 로메로", position: "DF", country: "아르헨티나", age: 27, rating: 88 },
            { name: "모하메드 쿠두스", position: "FW", country: "가나", age: 25, rating: 87 },
            { name: "도미닉 솔랑케", position: "FW", country: "잉글랜드", age: 27, rating: 86 },
            { name: "사비 시몬스", position: "MF", country: "네덜란드", age: 22, rating: 87 },
            { name: "양민혁", position: "FW", country: "대한민국", age: 19, rating: 85 },
            { name: "데쿤 쿨루셉스키", position: "MF", country: "스웨덴", age: 25, rating: 85 },
            { name: "페드로 포로", position: "DF", country: "스페인", age: 25, rating: 86 },
            { name: "미키 판더벤", position: "DF", country: "네덜란드", age: 24, rating: 86 },
            { name: "주앙 팔리냐", position: "MF", country: "포르투갈", age: 30, rating: 84 },
            { name: "굴리엘모 비카리오", position: "GK", country: "이탈리아", age: 28, rating: 84 },
            { name: "제임스 매디슨", position: "MF", country: "잉글랜드", age: 28, rating: 83 },
        ],
        description: "To Dare Is To Do - 스퍼스의 도전 정신"
    },
    "파리_생제르맹": {
        displayName: "파리 생제르맹", city: "파리", logoCode: "PSG", league: 1, budget: 2500,
        players: [
            { name: "우스만 뎀벨레", position: "FW", country: "프랑스", age: 28, rating: 95 },
            { name: "비티냐", position: "MF", country: "포르투갈", age: 25, rating: 93 },
            { name: "흐비차 크바라츠헬리아", position: "FW", country: "조지아", age: 24, rating: 93 },
            { name: "아슈라프 하키미", position: "DF", country: "모로코", age: 26, rating: 92 },
            { name: "누누 멘데스", position: "DF", country: "포르투갈", age: 23, rating: 91 },
            { name: "주앙 네베스", position: "MF", country: "포르투갈", age: 20, rating: 89 },
            { name: "데지레 두에", position: "FW", country: "프랑스", age: 20, rating: 89 },
            { name: "브래들리 바르콜라", position: "FW", country: "프랑스", age: 22, rating: 86 },
            { name: "루카 슈발리에", position: "GK", country: "프랑스", age: 24, rating: 85 },
            { name: "마르키뉴스", position: "DF", country: "브라질", age: 31, rating: 85 },
            { name: "파비안 루이스", position: "MF", country: "스페인", age: 29, rating: 83 },
            { name: "이강인", position: "MF", country: "대한민국", age: 24, rating: 84 },
        ],
        description: "파리의 별들이 빛나는 세계 최고의 무대"
    },
    "AC_밀란": {
        displayName: "AC 밀란", city: "밀라노", logoCode: "ACM", league: 1, budget: 700,
        players: [
            { name: "크리스천 풀리식", position: "FW", country: "미국", age: 26, rating: 90 },
            { name: "하파엘 레앙", position: "FW", country: "포르투갈", age: 26, rating: 89 },
            { name: "아드리앙 라비오", position: "MF", country: "프랑스", age: 30, rating: 86 },
            { name: "피카요 토모리", position: "DF", country: "잉글랜드", age: 27, rating: 85 },
            { name: "마이크 메냥", position: "GK", country: "프랑스", age: 30, rating: 85 },
            { name: "아르돈 야샤리", position: "MF", country: "스위스", age: 22, rating: 83 },
            { name: "산티아고 히메네스", position: "FW", country: "멕시코", age: 24, rating: 83 },
            { name: "루카 모드리치", position: "MF", country: "크로아티아", age: 39, rating: 85 },
            { name: "유수프 포파나", position: "MF", country: "프랑스", age: 26, rating: 82 },
            { name: "마테오 가비아", position: "DF", country: "이탈리아", age: 25, rating: 80 },
            { name: "루벤 로프터스치크", position: "MF", country: "잉글랜드", age: 29, rating: 81 },
            { name: "니클라스 퓔크루크", position: "FW", country: "독일", age: 32, rating: 81 },
        ],
        description: "로쏘네리의 전통과 명예를 이어가는 밀라노의 자존심"
    },
    "인터_밀란": {
        displayName: "인터 밀란", city: "밀라노", logoCode: "INT", league: 1, budget: 750,
        players: [
            { name: "니콜로 바렐라", position: "MF", country: "이탈리아", age: 28, rating: 91 },
            { name: "알레산드로 바스토니", position: "DF", country: "이탈리아", age: 26, rating: 90 },
            { name: "라우타로 마르티네스", position: "FW", country: "아르헨티나", age: 27, rating: 90 },
            { name: "하칸 찰하놀루", position: "MF", country: "튀르키예", age: 31, rating: 89 },
            { name: "덴젤 둠프리스", position: "DF", country: "네덜란드", age: 29, rating: 87 },
            { name: "마르쿠스 튀랑", position: "FW", country: "프랑스", age: 27, rating: 87 },
            { name: "페데리코 디마르코", position: "DF", country: "이탈리아", age: 27, rating: 87 },
            { name: "얀 조머", position: "GK", country: "스위스", age: 36, rating: 83 },
            { name: "프란체스코 아체르비", position: "DF", country: "이탈리아", age: 37, rating: 83 },
            { name: "다비데 프라테시", position: "MF", country: "이탈리아", age: 25, rating: 82 },
            { name: "뱅자맹 파바르", position: "DF", country: "프랑스", age: 29, rating: 81 },
            { name: "크리스티안 아슬라니", position: "MF", country: "알바니아", age: 23, rating: 79 },
        ],
        description: "네라주리의 위대한 전통을 이어가는 밀라노의 자존심"
    },
    "아스널": {
        displayName: "아스널", city: "런던", logoCode: "ARS", league: 1, budget: 1100,
        players: [
            { name: "데클란 라이스", position: "MF", country: "잉글랜드", age: 26, rating: 91 },
            { name: "가브리엘 마갈량이스", position: "DF", country: "브라질", age: 27, rating: 90 },
            { name: "빅토르 요케레스", position: "FW", country: "스웨덴", age: 27, rating: 90 },
            { name: "부카요 사카", position: "FW", country: "잉글랜드", age: 23, rating: 88 },
            { name: "마르틴 수비멘디", position: "MF", country: "스페인", age: 26, rating: 87 },
            { name: "마르틴 외데고르", position: "MF", country: "노르웨이", age: 26, rating: 86 },
            { name: "리카르도 칼라피오리", position: "DF", country: "이탈리아", age: 23, rating: 85 },
            { name: "위리엔 팀버르", position: "DF", country: "네덜란드", age: 24, rating: 85 },
            { name: "가브리엘 마르티넬리", position: "FW", country: "브라질", age: 24, rating: 85 },
            { name: "윌리엄 살리바", position: "DF", country: "프랑스", age: 24, rating: 85 },
            { name: "다비드 라야", position: "GK", country: "스페인", age: 29, rating: 85 },
            { name: "미켈 메리노", position: "MF", country: "스페인", age: 29, rating: 83 },
        ],
        description: "벵거볼의 아름다운 축구와 불굴의 정신력"
    },
    "나폴리": {
        displayName: "나폴리", city: "나폴리", logoCode: "NAP", league: 1, budget: 650,
        players: [
            { name: "스콧 맥토미니", position: "MF", country: "스코틀랜드", age: 28, rating: 92 },
            { name: "조반니 디 로렌초", position: "DF", country: "이탈리아", age: 31, rating: 87 },
            { name: "케빈 더브라위너", position: "MF", country: "벨기에", age: 34, rating: 87 },
            { name: "로멜루 루카쿠", position: "FW", country: "벨기에", age: 32, rating: 86 },
            { name: "알레산드로 부온조르노", position: "DF", country: "이탈리아", age: 26, rating: 85 },
            { name: "마테오 폴리타노", position: "FW", country: "이탈리아", age: 31, rating: 85 },
            { name: "자코모 라스파도리", position: "FW", country: "이탈리아", age: 25, rating: 85 },
            { name: "스타니슬라프 로보트카", position: "MF", country: "슬로바키아", age: 30, rating: 84 },
            { name: "마티아스 올리베라", position: "DF", country: "우루과이", age: 27, rating: 83 },
            { name: "아미르 라흐마니", position: "DF", country: "코소보", age: 31, rating: 82 },
            { name: "앙드레프랑크 잠보 앙귀사", position: "MF", country: "카메룬", age: 29, rating: 82 },
            { name: "알렉스 메렛", position: "GK", country: "이탈리아", age: 28, rating: 83 },
        ],
        description: "남부 이탈리아의 열정과 자존심을 대표하는 파르테노페이"
    },
    "첼시": {
        displayName: "첼시", city: "런던", logoCode: "CHE", league: 1, budget: 1800,
        players: [
            { name: "모이세스 카이세도", position: "MF", country: "에콰도르", age: 23, rating: 91 },
            { name: "엔조 페르난데스", position: "MF", country: "아르헨티나", age: 24, rating: 90 },
            { name: "콜 파머", position: "MF", country: "잉글랜드", age: 23, rating: 88 },
            { name: "쿠쿠렐라", position: "DF", country: "스페인", age: 27, rating: 88 },
            { name: "리스 제임스", position: "DF", country: "잉글랜드", age: 25, rating: 88 },
            { name: "안드레이 산투스", position: "MF", country: "브라질", age: 21, rating: 86 },
            { name: "주앙 페드루", position: "FW", country: "브라질", age: 24, rating: 86 },
            { name: "리바이 콜윌", position: "DF", country: "잉글랜드", age: 22, rating: 84 },
            { name: "말로 귀스토", position: "DF", country: "프랑스", age: 22, rating: 84 },
            { name: "페드루 네투", position: "FW", country: "포르투갈", age: 25, rating: 83 },
            { name: "제이미 기튼스", position: "FW", country: "잉글랜드", age: 20, rating: 83 },
            { name: "로메우 라비아", position: "MF", country: "벨기에", age: 21, rating: 82 },
        ],
        description: "블루스의 강력한 투지와 승부근성"
    },
    "바이에른_뮌헨": {
        displayName: "바이에른 뮌헨", city: "뮌헨", logoCode: "BAY", league: 1, budget: 1400,
        players: [
            { name: "해리 케인", position: "FW", country: "잉글랜드", age: 32, rating: 93 },
            { name: "요주아 키미히", position: "MF", country: "독일", age: 30, rating: 90 },
            { name: "자말 무시알라", position: "MF", country: "독일", age: 22, rating: 89 },
            { name: "마이클 올리세", position: "FW", country: "프랑스", age: 23, rating: 88 },
            { name: "알폰소 데이비스", position: "DF", country: "캐나다", age: 24, rating: 87 },
            { name: "루이스 디아스", position: "FW", country: "콜롬비아", age: 28, rating: 87 },
            { name: "요나탄 타", position: "DF", country: "독일", age: 29, rating: 87 },
            { name: "김민재", position: "DF", country: "대한민국", age: 28, rating: 86 },
            { name: "다요 우파메카노", position: "DF", country: "프랑스", age: 26, rating: 85 },
            { name: "레온 고레츠카", position: "MF", country: "독일", age: 30, rating: 85 },
            { name: "알렉산다르 파블로비치", position: "MF", country: "독일", age: 21, rating: 85 },
            { name: "마누엘 노이어", position: "GK", country: "독일", age: 39, rating: 83 },
        ],
        description: "독일 축구의 자존심이자 뮌헨의 왕자들"
    },
    "아틀레티코_마드리드": {
        displayName: "아틀레티코 마드리드", city: "마드리드", logoCode: "ATM", league: 1, budget: 850,
        players: [
            { name: "앙투안 그리즈만", position: "FW", country: "프랑스", age: 34, rating: 90 },
            { name: "훌리안 알바레스", position: "FW", country: "아르헨티나", age: 25, rating: 90 },
            { name: "클레망 랑글레", position: "DF", country: "프랑스", age: 30, rating: 87 },
            { name: "아데몰라 루크먼", position: "FW", country: "나이지리아", age: 28, rating: 86 },
            { name: "알렉스 바에나", position: "MF", country: "스페인", age: 24, rating: 86 },
            { name: "파블로 바리오스", position: "MF", country: "스페인", age: 22, rating: 85 },
            { name: "줄리아노 시메오네", position: "FW", country: "아르헨티나", age: 22, rating: 85 },
            { name: "호세 히메네스", position: "DF", country: "우루과이", age: 30, rating: 84 },
            { name: "마르코스 요렌테", position: "MF", country: "스페인", age: 30, rating: 84 },
            { name: "나우엘 몰리나", position: "DF", country: "아르헨티나", age: 27, rating: 82 },
            { name: "얀 오블락", position: "GK", country: "슬로베니아", age: 32, rating: 86 },
            { name: "코케", position: "MF", country: "스페인", age: 33, rating: 82 },
        ],
        description: "콜치오네로스의 불굴의 투지와 승부욕"
    },
    "도르트문트": {
        displayName: "도르트문트", city: "도르트문트", logoCode: "BVB", league: 1, budget: 900,
        players: [
            { name: "세루 기라시", position: "FW", country: "기니", age: 29, rating: 91 },
            { name: "니코 슐로터베크", position: "DF", country: "독일", age: 25, rating: 86 },
            { name: "율리안 브란트", position: "MF", country: "독일", age: 29, rating: 86 },
            { name: "카림 아데예미", position: "FW", country: "독일", age: 23, rating: 85 },
            { name: "그레고어 코벨", position: "GK", country: "스위스", age: 27, rating: 85 },
            { name: "파스칼 그로스", position: "MF", country: "독일", age: 34, rating: 83 },
            { name: "율리안 뤼에르손", position: "DF", country: "노르웨이", age: 27, rating: 84 },
            { name: "마르셀 자비처", position: "MF", country: "오스트리아", age: 31, rating: 81 },
            { name: "라미 벤세바이니", position: "DF", country: "알제리", age: 30, rating: 81 },
            { name: "펠릭스 은메차", position: "MF", country: "독일", age: 24, rating: 80 },
            { name: "막시밀리안 바이어", position: "FW", country: "독일", age: 22, rating: 80 },
            { name: "얀 코투", position: "DF", country: "브라질", age: 23, rating: 82 },
        ],
        description: "보루시아의 노란 벽과 함께하는 젊은 열정"
    },
    // 2부 리그
    "유벤투스": {
        displayName: "유벤투스", city: "토리노", logoCode: "JUV", league: 2, budget: 800,
        players: [
            { name: "케난 일디즈", position: "FW", country: "튀르키예", age: 20, rating: 87 },
            { name: "로이스 오펜다", position: "FW", country: "벨기에", age: 25, rating: 87 },
            { name: "조너선 데이비드", position: "FW", country: "캐나다", age: 25, rating: 86 },
            { name: "안드레아 캄비아소", position: "DF", country: "이탈리아", age: 25, rating: 86 },
            { name: "도글라스 루이스", position: "MF", country: "브라질", age: 27, rating: 85 },
            { name: "글레이송 브레메르", position: "DF", country: "브라질", age: 28, rating: 85 },
            { name: "퇸 코프메이너르스", position: "MF", country: "네덜란드", age: 27, rating: 85 },
            { name: "두샨 블라호비치", position: "FW", country: "세르비아", age: 25, rating: 84 },
            { name: "케프랑 튀랑", position: "MF", country: "프랑스", age: 24, rating: 84 },
            { name: "페데리코 가티", position: "DF", country: "이탈리아", age: 27, rating: 83 },
            { name: "주앙 마리우", position: "DF", country: "포르투갈", age: 25, rating: 83 },
            { name: "미켈레 디그레고리오", position: "GK", country: "이탈리아", age: 28, rating: 80 },
        ],
        description: "비앙코네리의 전통과 명예를 되찾기 위한 도전"
    },
    "뉴캐슬_유나이티드": {
        displayName: "뉴캐슬 유나이티드", city: "뉴캐슬", logoCode: "NEW", league: 2, budget: 1300,
        players: [
            { name: "브루누 기마랑이스", position: "MF", country: "브라질", age: 27, rating: 90 },
            { name: "산드로 토날리", position: "MF", country: "이탈리아", age: 25, rating: 89 },
            { name: "앤서니 고든", position: "FW", country: "잉글랜드", age: 24, rating: 87 },
            { name: "티노 리브라멘토", position: "DF", country: "잉글랜드", age: 22, rating: 85 },
            { name: "닉 볼테마데", position: "FW", country: "독일", age: 23, rating: 85 },
            { name: "루이스 홀", position: "DF", country: "잉글랜드", age: 20, rating: 84 },
            { name: "파비안 셰어", position: "DF", country: "스위스", age: 33, rating: 84 },
            { name: "조엘린통", position: "MF", country: "브라질", age: 28, rating: 84 },
            { name: "제이미 머피", position: "FW", country: "잉글랜드", age: 30, rating: 84 },
            { name: "닉 포프", position: "GK", country: "잉글랜드", age: 33, rating: 83 },
            { name: "스벤 보트만", position: "DF", country: "네덜란드", age: 25, rating: 83 },
            { name: "키어런 트리피어", position: "DF", country: "잉글랜드", age: 34, rating: 82 },
        ],
        description: "마그파이스의 재기를 꿈꾸는 타인 사이드의 열정"
    },
    "아스톤_빌라": {
        displayName: "아스톤 빌라", city: "버밍엄", logoCode: "AVL", league: 2, budget: 700,
        players: [
            { name: "유리 틸레만스", position: "MF", country: "벨기에", age: 28, rating: 88 },
            { name: "올리 왓킨스", position: "FW", country: "잉글랜드", age: 29, rating: 87 },
            { name: "모건 로저스", position: "FW", country: "잉글랜드", age: 23, rating: 86 },
            { name: "파우 토레스", position: "DF", country: "스페인", age: 28, rating: 85 },
            { name: "에밀리아노 마르티네스", position: "GK", country: "아르헨티나", age: 32, rating: 85 },
            { name: "아마두 오나나", position: "MF", country: "벨기에", age: 23, rating: 84 },
            { name: "이안 마트센", position: "DF", country: "네덜란드", age: 23, rating: 84 },
            { name: "도니얼 말런", position: "FW", country: "네덜란드", age: 26, rating: 83 },
            { name: "매티 캐시", position: "DF", country: "폴란드", age: 27, rating: 83 },
            { name: "존 맥긴", position: "MF", country: "스코틀랜드", age: 30, rating: 82 },
            { name: "부바카르 카마라", position: "MF", country: "프랑스", age: 25, rating: 82 },
            { name: "에반 게상", position: "FW", country: "코트디부아르", age: 24, rating: 82 },
        ],
        description: "빌라 파크의 자존심을 되찾기 위한 클라렛과 블루의 부활"
    },
    "라이프치히": {
        displayName: "라이프치히", city: "라이프치히", logoCode: "LEI", league: 2, budget: 600,
        players: [
            { name: "다비트 라움", position: "DF", country: "독일", age: 27, rating: 84 },
            { name: "뤼츠하럴 헤이르트라위다", position: "DF", country: "네덜란드", age: 25, rating: 83 },
            { name: "빌리 오르반", position: "DF", country: "헝가리", age: 32, rating: 83 },
            { name: "안토니오 누사", position: "FW", country: "노르웨이", age: 20, rating: 83 },
            { name: "크사버 슐라거", position: "MF", country: "오스트리아", age: 27, rating: 82 },
            { name: "아마두 아이다라", position: "MF", country: "말리", age: 27, rating: 81 },
            { name: "페테르 굴라치", position: "GK", country: "헝가리", age: 35, rating: 81 },
            { name: "티모 베르너", position: "FW", country: "독일", age: 30, rating: 82 },
            { name: "호물루", position: "FW", country: "브라질", age: 24, rating: 82 },
            { name: "니콜라스 자이발트", position: "MF", country: "오스트리아", age: 24, rating: 80 },
            { name: "요한 바카요코", position: "FW", country: "벨기에", age: 22, rating: 81 },
            { name: "마르턴 판더보르트", position: "GK", country: "벨기에", age: 23, rating: 81 },
        ],
        description: "라이프치히의 젊은 에너지와 혁신적인 축구"
    },
    "세비야": {
        displayName: "세비야", city: "세비야", logoCode: "SEV", league: 2, budget: 450,
        players: [
            { name: "도디 루케바키오", position: "FW", country: "벨기에", age: 27, rating: 84 },
            { name: "뤼시앵 아구메", position: "MF", country: "프랑스", age: 23, rating: 83 },
            { name: "지브릴 소우", position: "MF", country: "스위스", age: 28, rating: 82 },
            { name: "호세 앙헬 카르모나", position: "DF", country: "스페인", age: 23, rating: 82 },
            { name: "키케 살라스", position: "DF", country: "스페인", age: 23, rating: 79 },
            { name: "루벤 바르가스", position: "FW", country: "스위스", age: 26, rating: 78 },
            { name: "탕기 니안주", position: "DF", country: "프랑스", age: 23, rating: 79 },
            { name: "네마냐 구데이", position: "MF", country: "세르비아", age: 33, rating: 78 },
            { name: "아드리아 페드로사", position: "DF", country: "스페인", age: 27, rating: 76 },
            { name: "외르얀 뉠란", position: "GK", country: "노르웨이", age: 34, rating: 75 },
            { name: "이삭 로메로", position: "FW", country: "스페인", age: 25, rating: 74 },
            { name: "알바로 페르난데스", position: "GK", country: "스페인", age: 27, rating: 73 },
        ],
        description: "네르비온의 열정을 되살리려는 세비야의 도전"
    },
    "아약스": {
        displayName: "아약스", city: "암스테르담", logoCode: "AJA", league: 2, budget: 350,
        players: [
            { name: "브라이언 브로비", position: "FW", country: "네덜란드", age: 23, rating: 85 },
            { name: "케네스 테일러", position: "MF", country: "네덜란드", age: 23, rating: 82 },
            { name: "스티븐 베르하위스", position: "FW", country: "네덜란드", age: 33, rating: 83 },
            { name: "요시프 슈탈로", position: "DF", country: "크로아티아", age: 25, rating: 81 },
            { name: "유리 바스", position: "DF", country: "네덜란드", age: 22, rating: 76 },
            { name: "올리베르 에드바르센", position: "FW", country: "노르웨이", age: 26, rating: 77 },
            { name: "데이비 클라센", position: "MF", country: "네덜란드", age: 32, rating: 78 },
            { name: "안톤 고에이", position: "DF", country: "덴마크", age: 22, rating: 74 },
            { name: "루카스 호자", position: "DF", country: "브라질", age: 25, rating: 73 },
            { name: "베르트랑 트라오레", position: "FW", country: "부르키나파소", age: 29, rating: 73 },
            { name: "렘코 파스베이르", position: "GK", country: "네덜란드", age: 41, rating: 75 },
            { name: "오언 베인달", position: "DF", country: "네덜란드", age: 25, rating: 71 },
        ],
        description: "암스테르담의 자존심을 되찾기 위한 토털 풋볼의 부활"
    },
    "AS_로마": {
        displayName: "AS 로마", city: "로마", logoCode: "ROM", league: 2, budget: 500,
        players: [
            { name: "아르템 도우비크", position: "FW", country: "우크라이나", age: 28, rating: 85 },
            { name: "마티아스 소울레", position: "FW", country: "아르헨티나", age: 22, rating: 86 },
            { name: "에방 은디카", position: "DF", country: "프랑스", age: 25, rating: 84 },
            { name: "로렌초 펠레그리니", position: "MF", country: "이탈리아", age: 29, rating: 83 },
            { name: "잔루카 만치니", position: "DF", country: "이탈리아", age: 29, rating: 83 },
            { name: "마누 코네", position: "MF", country: "프랑스", age: 24, rating: 82 },
            { name: "닐 엘 야누이", position: "MF", country: "프랑스", age: 21, rating: 83 },
            { name: "파울로 디발라", position: "FW", country: "아르헨티나", age: 31, rating: 84 },
            { name: "앙헬리뇨", position: "DF", country: "스페인", age: 28, rating: 82 },
            { name: "레온 베일리", position: "FW", country: "자메이카", age: 27, rating: 82 },
            { name: "밀레 스빌라르", position: "GK", country: "세르비아", age: 25, rating: 75 },
            { name: "스테판 엘샤라위", position: "FW", country: "이탈리아", age: 32, rating: 82 },
        ],
        description: "로마의 영광을 되찾기 위한 잘로로시의 도전"
    },
    "레버쿠젠": {
        displayName: "레버쿠젠", city: "레버쿠젠", logoCode: "B04", league: 2, budget: 550,
        players: [
            { name: "파트리크 시크", position: "FW", country: "체코", age: 29, rating: 86 },
            { name: "빅터 보니페이스", position: "FW", country: "나이지리아", age: 24, rating: 85 },
            { name: "에드몽 탑소바", position: "DF", country: "부르키나파소", age: 26, rating: 85 },
            { name: "알레한드로 그리말도", position: "DF", country: "스페인", age: 29, rating: 85 },
            { name: "말릭 틸먼", position: "MF", country: "미국", age: 23, rating: 86 },
            { name: "로익 바데", position: "DF", country: "프랑스", age: 25, rating: 83 },
            { name: "에제키엘 팔라시오스", position: "MF", country: "아르헨티나", age: 26, rating: 82 },
            { name: "요나스 호프만", position: "MF", country: "독일", age: 33, rating: 81 },
            { name: "로베르트 안드리히", position: "MF", country: "독일", age: 30, rating: 79 },
            { name: "마르크 플레컨", position: "GK", country: "네덜란드", age: 32, rating: 79 },
            { name: "루카스 바스케스", position: "DF", country: "스페인", age: 34, rating: 82 },
            { name: "마리오 에르모소", position: "DF", country: "스페인", age: 30, rating: 77 },
        ],
        description: "바이엘 레버쿠젠의 무패 신화를 이어가려는 의지"
    },
    "스포르팅_CP": {
        displayName: "스포르팅 CP", city: "리스본", logoCode: "SCP", league: 2, budget: 300,
        players: [
            { name: "프란시스쿠 트링캉", position: "FW", country: "포르투갈", age: 25, rating: 86 },
            { name: "페드루 곤살베스", position: "FW", country: "포르투갈", age: 27, rating: 85 },
            { name: "곤살루 이나시우", position: "DF", country: "포르투갈", age: 23, rating: 84 },
            { name: "우스망 디오망데", position: "DF", country: "코트디부아르", age: 21, rating: 83 },
            { name: "모르텐 히울만", position: "MF", country: "덴마크", age: 26, rating: 83 },
            { name: "누누 산투스", position: "MF", country: "포르투갈", age: 30, rating: 82 },
            { name: "모리타 히데마사", position: "MF", country: "일본", age: 30, rating: 77 },
            { name: "후이 실바", position: "GK", country: "포르투갈", age: 31, rating: 74 },
            { name: "마테우스 헤이스", position: "DF", country: "브라질", age: 30, rating: 74 },
            { name: "제리 신트쥐스터", position: "DF", country: "네덜란드", age: 28, rating: 72 },
            { name: "프랑코 이스라엘", position: "GK", country: "우루과이", age: 25, rating: 72 },
            { name: "지오바니 켄다", position: "FW", country: "포르투갈", age: 18, rating: 83 },
        ],
        description: "리스본의 사자들이 다시 한번 포효하는 스포르팅의 부활"
    },
    "벤피카": {
        displayName: "벤피카", city: "리스본", logoCode: "BEN", league: 2, budget: 320,
        players: [
            { name: "반젤리스 파블리디스", position: "FW", country: "그리스", age: 26, rating: 86 },
            { name: "오르쿤 쾨크취", position: "MF", country: "튀르키예", age: 24, rating: 85 },
            { name: "안토니우 실바", position: "DF", country: "포르투갈", age: 21, rating: 84 },
            { name: "프레드리크 아우르스네스", position: "MF", country: "노르웨이", age: 29, rating: 84 },
            { name: "케렘 아크튀르크올루", position: "FW", country: "튀르키예", age: 26, rating: 84 },
            { name: "알렉산데르 바", position: "DF", country: "덴마크", age: 27, rating: 82 },
            { name: "엔조 바레네체아", position: "MF", country: "아르헨티나", age: 24, rating: 82 },
            { name: "플로렌티누 루이스", position: "MF", country: "포르투갈", age: 25, rating: 82 },
            { name: "헤나투 산체스", position: "MF", country: "포르투갈", age: 27, rating: 82 },
            { name: "브루마", position: "FW", country: "포르투갈", age: 30, rating: 82 },
            { name: "아나톨리 트루빈", position: "GK", country: "우크라이나", age: 24, rating: 79 },
            { name: "니콜라스 오타멘디", position: "DF", country: "아르헨티나", age: 37, rating: 78 },
        ],
        description: "이글스의 자존심과 전통을 이어가는 벤피카의 도전"
    },
    "셀틱": {
        displayName: "셀틱", city: "글래스고", logoCode: "CEL", league: 2, budget: 200,
        players: [
            { name: "앨리스테어 존스턴", position: "DF", country: "캐나다", age: 26, rating: 81 },
            { name: "마에다 다이젠", position: "FW", country: "일본", age: 27, rating: 77 },
            { name: "루크 매코완", position: "MF", country: "스코틀랜드", age: 27, rating: 75 },
            { name: "이나무라 하야토", position: "DF", country: "일본", age: 24, rating: 75 },
            { name: "칼럼 맥그리거", position: "MF", country: "스코틀랜드", age: 32, rating: 76 },
            { name: "키어런 티어니", position: "DF", country: "스코틀랜드", age: 28, rating: 76 },
            { name: "조타", position: "FW", country: "포르투갈", age: 26, rating: 76 },
            { name: "양현준", position: "FW", country: "대한민국", age: 23, rating: 76 },
            { name: "카스페르 슈마이켈", position: "GK", country: "덴마크", age: 38, rating: 72 },
            { name: "리암 스케일스", position: "DF", country: "아일랜드", age: 26, rating: 76 },
            { name: "하타테 레오", position: "MF", country: "일본", age: 27, rating: 74 },
            { name: "아담 이다", position: "FW", country: "아일랜드", age: 24, rating: 73 },
        ],
        description: "글래스고의 녹색과 흰색 호프스를 위한 셀틱의 전통"
    },
    "페예노르트": {
        displayName: "페예노르트", city: "로테르담", logoCode: "FEY", league: 2, budget: 250,
        players: [
            { name: "황인범", position: "MF", country: "대한민국", age: 28, rating: 80 },
            { name: "셈 스테인", position: "MF", country: "네덜란드", age: 23, rating: 84 },
            { name: "야쿠프 모데르", position: "MF", country: "폴란드", age: 26, rating: 82 },
            { name: "퀸턴 팀버르", position: "MF", country: "네덜란드", age: 24, rating: 82 },
            { name: "토마스 베일런", position: "DF", country: "네덜란드", age: 23, rating: 77 },
            { name: "헤이스 스말", position: "DF", country: "네덜란드", age: 27, rating: 76 },
            { name: "루시아노 발렌테", position: "MF", country: "네덜란드", age: 21, rating: 78 },
            { name: "아니스 하지 무사", position: "FW", country: "알제리", age: 23, rating: 79 },
            { name: "카스퍼르 텡스테트", position: "FW", country: "덴마크", age: 25, rating: 76 },
            { name: "와타나베 츠요시", position: "DF", country: "일본", age: 28, rating: 73 },
            { name: "티몬 벨렌로이터", position: "GK", country: "독일", age: 29, rating: 75 },
            { name: "배승균", position: "MF", country: "대한민국", age: 18, rating: 66 },
        ],
        description: "로테르담의 자존심을 되찾기 위한 페예노르트의 열정"
    },
    "올랭피크_드_마르세유": {
        displayName: "올랭피크 드 마르세유", city: "마르세유", logoCode: "MAR", league: 2, budget: 400,
        players: [
            { name: "메이슨 그린우드", position: "FW", country: "잉글랜드", age: 23, rating: 87 },
            { name: "피에르에밀 호이비에르", position: "MF", country: "덴마크", age: 30, rating: 85 },
            { name: "레오나르도 발레르디", position: "DF", country: "아르헨티나", age: 26, rating: 85 },
            { name: "이고르 파이샹", position: "FW", country: "브라질", age: 25, rating: 84 },
            { name: "파쿤도 메디나", position: "DF", country: "아르헨티나", age: 26, rating: 83 },
            { name: "아민 구이리", position: "FW", country: "프랑스", age: 25, rating: 81 },
            { name: "피에르 에메릭 오바메양", position: "FW", country: "가봉", age: 36, rating: 83 },
            { name: "오렐 망갈라", position: "MF", country: "벨기에", age: 28, rating: 77 },
            { name: "울리세스 가르시아", position: "DF", country: "스위스", age: 29, rating: 78 },
            { name: "아미르 무리요", position: "DF", country: "파나마", age: 29, rating: 82 },
            { name: "헤로니모 룰리", position: "GK", country: "아르헨티나", age: 33, rating: 78 },
            { name: "이스마엘 베나세르", position: "MF", country: "알제리", age: 27, rating: 78 },
        ],
        description: "지중해의 열정과 프랑스의 자존심을 대표하는 마르세유"
    },
    // 3부 리그
    "FC_서울": {
        displayName: "FC 서울", city: "서울", logoCode: "FCS", league: 3, budget: 50,
        players: [
            { name: "린가드", position: "MF", country: "잉글랜드", age: 32, rating: 82 },
            { name: "정승원", position: "MF", country: "대한민국", age: 28, rating: 79 },
            { name: "이승모", position: "MF", country: "대한민국", age: 27, rating: 76 },
            { name: "야잔", position: "DF", country: "요르단", age: 29, rating: 78 },
            { name: "이상민", position: "DF", country: "대한민국", age: 27, rating: 75 },
            { name: "정태욱", position: "DF", country: "대한민국", age: 28, rating: 75 },
            { name: "클리말라", position: "FW", country: "폴란드", age: 26, rating: 76 },
            { name: "둑스", position: "FW", country: "크로아티아", age: 31, rating: 77 },
            { name: "조영욱", position: "FW", country: "대한민국", age: 26, rating: 74 },
            { name: "이한도", position: "DF", country: "대한민국", age: 31, rating: 76 },
            { name: "강현무", position: "GK", country: "대한민국", age: 30, rating: 73 },
            { name: "최준", position: "DF", country: "대한민국", age: 26, rating: 73 },
        ],
        description: "대한민국 수도의 자존심, 끊임없는 도전정신"
    },
    "갈라타사라이": {
        displayName: "갈라타사라이", city: "이스탄불", logoCode: "GAL", league: 3, budget: 150,
        players: [
            { name: "빅터 오시멘", position: "FW", country: "나이지리아", age: 26, rating: 85 },
            { name: "리로이 사네", position: "MF", country: "독일", age: 29, rating: 82 },
            { name: "마우로 이카르디", position: "FW", country: "아르헨티나", age: 32, rating: 79 },
            { name: "다빈손 산체스", position: "DF", country: "콜롬비아", age: 29, rating: 78 },
            { name: "이스마일 자콥스", position: "DF", country: "세네갈", age: 25, rating: 76 },
            { name: "루카스 토레이라", position: "MF", country: "우루과이", age: 29, rating: 76 },
            { name: "가브리에우 사라", position: "MF", country: "브라질", age: 26, rating: 76 },
            { name: "케렘 데미르바이", position: "MF", country: "독일", age: 32, rating: 76 },
            { name: "롤런드 셜러이", position: "FW", country: "헝가리", age: 28, rating: 77 },
            { name: "데릭 쾬", position: "DF", country: "독일", age: 30, rating: 75 },
            { name: "마리오 르미나", position: "MF", country: "가봉", age: 31, rating: 74 },
            { name: "페르난도 무슬레라", position: "GK", country: "우루과이", age: 39, rating: 74 },
        ],
        description: "이스탄불의 사자들이 보여주는 터키 축구의 자존심"
    },
    "알_힐랄": {
        displayName: "알 힐랄", city: "리야드", logoCode: "HIL", league: 3, budget: 1200,
        players: [
            { name: "테오 에르난데스", position: "DF", country: "프랑스", age: 28, rating: 84 },
            { name: "후벵 네베스", position: "MF", country: "포르투갈", age: 29, rating: 83 },
            { name: "세르게이 밀린코비치-사비치", position: "MF", country: "세르비아", age: 31, rating: 82 },
            { name: "카림 벤제마", position: "FW", country: "프랑스", age: 38, rating: 82 },
            { name: "칼리두 쿨리발리", position: "DF", country: "세네갈", age: 34, rating: 81 },
            { name: "야신 부누", position: "GK", country: "모로코", age: 35, rating: 79 },
            { name: "다르윈 누녜스", position: "FW", country: "우루과이", age: 26, rating: 82 },
            { name: "마르코스 레오나르두", position: "FW", country: "브라질", age: 22, rating: 77 },
            { name: "파블로 마리", position: "DF", country: "스페인", age: 32, rating: 75 },
            { name: "살렘 알 다우사리", position: "MF", country: "사우디아라비아", age: 34, rating: 73 },
            { name: "하산 알 탐박티", position: "DF", country: "사우디아라비아", age: 27, rating: 72 },
            { name: "모하메드 칸노", position: "MF", country: "사우디아라비아", age: 31, rating: 74 },
        ],
        description: "사우디아라비아의 킹 클럽이 보여주는 중동 축구의 힘"
    },
    "알_나스르": {
        displayName: "알 나스르", city: "리야드", logoCode: "NAS", league: 3, budget: 1000,
        players: [
            { name: "크리스티아누 호날두", position: "FW", country: "포르투갈", age: 41, rating: 86 },
            { name: "사디오 마네", position: "FW", country: "세네갈", age: 34, rating: 82 },
            { name: "주앙 펠릭스", position: "FW", country: "포르투갈", age: 26, rating: 80 },
            { name: "킹슬리 코망", position: "FW", country: "프랑스", age: 30, rating: 81 },
            { name: "마르첼로 브로조비치", position: "MF", country: "크로아티아", age: 33, rating: 80 },
            { name: "이니고 마르티네스", position: "DF", country: "스페인", age: 35, rating: 78 },
            { name: "모하메드 시마칸", position: "DF", country: "프랑스", age: 26, rating: 79 },
            { name: "벤투", position: "GK", country: "브라질", age: 27, rating: 79 },
            { name: "술탄 알 간남", position: "DF", country: "사우디아라비아", age: 32, rating: 72 },
            { name: "사미 알 나지", position: "MF", country: "사우디아라비아", age: 29, rating: 71 },
            { name: "압둘레라 알 암리", position: "DF", country: "사우디아라비아", age: 29, rating: 71 },
            { name: "알리 알 하산", position: "MF", country: "사우디아라비아", age: 29, rating: 71 },
        ],
        description: "크리스티아누 호날두가 새로운 도전을 펼치는 무대"
    },
    "미국_연합": {
        displayName: "미국 연합", city: "워싱턴 D.C.", logoCode: "AME", league: 3, budget: 350,
        players: [
            { name: "리오넬 메시", position: "FW", country: "아르헨티나", age: 38, rating: 88 },
            { name: "루이스 수아레스", position: "FW", country: "우루과이", age: 38, rating: 81 },
            { name: "로드리고 데 파울", position: "MF", country: "아르헨티나", age: 31, rating: 83 },
            { name: "세르히오 부스케츠", position: "MF", country: "스페인", age: 37, rating: 79 },
            { name: "조르디 알바", position: "DF", country: "스페인", age: 36, rating: 76 },
            { name: "드니 부앙가", position: "FW", country: "가봉", age: 30, rating: 80 },
            { name: "로렌초 인시녜", position: "FW", country: "이탈리아", age: 34, rating: 77 },
            { name: "카이 바그너", position: "DF", country: "독일", age: 32, rating: 75 },
            { name: "루시아노 아코스타", position: "MF", country: "아르헨티나", age: 31, rating: 76 },
            { name: "카를레스 길", position: "MF", country: "스페인", age: 32, rating: 75 },
            { name: "마르텐 파에스", position: "GK", country: "네덜란드", age: 27, rating: 73 },
            { name: "워커 짐머만", position: "DF", country: "미국", age: 32, rating: 74 },
        ],
        description: "메시의 마법이 펼쳐지는 MLS의 화려한 무대"
    },
    "전북_현대": {
        displayName: "전북 현대", city: "전주", logoCode: "JEO", league: 3, budget: 60,
        players: [
            { name: "이승우", position: "FW", country: "대한민국", age: 28, rating: 78 },
            { name: "티아고", position: "FW", country: "브라질", age: 33, rating: 79 },
            { name: "콤파뇨", position: "FW", country: "이탈리아", age: 30, rating: 79 },
            { name: "오베르당", position: "MF", country: "브라질", age: 31, rating: 77 },
            { name: "모따", position: "FW", country: "브라질", age: 30, rating: 77 },
            { name: "감보아", position: "MF", country: "포르투갈", age: 30, rating: 74 },
            { name: "이동준", position: "FW", country: "대한민국", age: 29, rating: 76 },
            { name: "박지수", position: "DF", country: "대한민국", age: 32, rating: 78 },
            { name: "김영빈", position: "DF", country: "대한민국", age: 35, rating: 74 },
            { name: "강상윤", position: "MF", country: "대한민국", age: 22, rating: 73 },
            { name: "송범근", position: "GK", country: "대한민국", age: 29, rating: 72 },
            { name: "이영재", position: "MF", country: "대한민국", age: 32, rating: 74 },
        ],
        description: "한국 축구의 명문, 전북의 자부심과 전통"
    },
    "울산_현대": {
        displayName: "울산 HD", city: "울산", logoCode: "ULS", league: 3, budget: 70,
        players: [
            { name: "이동경", position: "MF", country: "대한민국", age: 29, rating: 78 },
            { name: "말컹", position: "FW", country: "브라질", age: 32, rating: 78 },
            { name: "조현우", position: "GK", country: "대한민국", age: 35, rating: 76 },
            { name: "보야니치", position: "MF", country: "스웨덴", age: 32, rating: 77 },
            { name: "야고", position: "FW", country: "브라질", age: 27, rating: 75 },
            { name: "에릭", position: "MF", country: "브라질", age: 29, rating: 75 },
            { name: "정승현", position: "DF", country: "대한민국", age: 32, rating: 75 },
            { name: "강상우", position: "DF", country: "대한민국", age: 33, rating: 74 },
            { name: "이진현", position: "MF", country: "대한민국", age: 29, rating: 73 },
            { name: "이희균", position: "MF", country: "대한민국", age: 28, rating: 73 },
            { name: "이규성", position: "MF", country: "대한민국", age: 32, rating: 73 },
            { name: "허율", position: "FW", country: "대한민국", age: 25, rating: 72 },
        ],
        description: "공업도시 울산의 자존심, 현대의 힘찬 질주"
    },
    "포항_스틸러스": {
        displayName: "포항 스틸러스", city: "포항", logoCode: "PHS", league: 3, budget: 40,
        players: [
            { name: "조르지", position: "FW", country: "브라질", age: 27, rating: 77 },
            { name: "주닝요", position: "FW", country: "브라질", age: 29, rating: 76 },
            { name: "기성용", position: "MF", country: "대한민국", age: 37, rating: 72 },
            { name: "윤평국", position: "GK", country: "대한민국", age: 34, rating: 74 },
            { name: "전민광", position: "DF", country: "대한민국", age: 33, rating: 73 },
            { name: "니시야 켄토", position: "DF", country: "일본", age: 27, rating: 73 },
            { name: "황재환", position: "FW", country: "대한민국", age: 25, rating: 71 },
            { name: "트란지스카", position: "FW", country: "독일", age: 25, rating: 74 },
            { name: "어정원", position: "DF", country: "대한민국", age: 27, rating: 72 },
            { name: "김인성", position: "FW", country: "대한민국", age: 37, rating: 73 },
            { name: "황인재", position: "GK", country: "대한민국", age: 32, rating: 72 },
            { name: "박찬용", position: "DF", country: "대한민국", age: 30, rating: 72 },
        ],
        description: "철강도시 포항의 강철 같은 의지와 투혼"
    },
    "광주_FC": {
        displayName: "광주 FC", city: "광주", logoCode: "GWA", league: 3, budget: 20,
        players: [
            { name: "프리드욘슨", position: "FW", country: "아이슬란드", age: 33, rating: 75 },
            { name: "최경록", position: "MF", country: "대한민국", age: 31, rating: 73 },
            { name: "하승운", position: "FW", country: "대한민국", age: 28, rating: 72 },
            { name: "이민기", position: "DF", country: "대한민국", age: 33, rating: 72 },
            { name: "임승겸", position: "DF", country: "대한민국", age: 31, rating: 72 },
            { name: "신창무", position: "FW", country: "대한민국", age: 34, rating: 71 },
            { name: "민상기", position: "DF", country: "대한민국", age: 35, rating: 71 },
            { name: "주세종", position: "MF", country: "대한민국", age: 36, rating: 71 },
            { name: "안영규", position: "DF", country: "대한민국", age: 37, rating: 70 },
            { name: "유제호", position: "MF", country: "대한민국", age: 26, rating: 70 },
            { name: "박정인", position: "FW", country: "대한민국", age: 26, rating: 71 },
            { name: "김경민", position: "GK", country: "대한민국", age: 35, rating: 73 },
        ],
        description: "광주의 열정과 호남의 축구 정신을 이어가는 팀"
    },
    "리옹": {
        displayName: "리옹", city: "리옹", logoCode: "OLY", league: 3, budget: 250,
        players: [
            { name: "엔드릭", position: "FW", country: "브라질", age: 20, rating: 80 },
            { name: "코랑탱 톨리소", position: "MF", country: "프랑스", age: 32, rating: 79 },
            { name: "오렐 망갈라", position: "MF", country: "벨기에", age: 28, rating: 77 },
            { name: "니콜라스 탈리아피코", position: "DF", country: "아르헨티나", age: 34, rating: 78 },
            { name: "아브네르 비니시우스", position: "DF", country: "브라질", age: 26, rating: 77 },
            { name: "태너 테스만", position: "MF", country: "미국", age: 25, rating: 75 },
            { name: "무사 니아카테", position: "DF", country: "세네갈", age: 30, rating: 76 },
            { name: "파벨 슐츠", position: "MF", country: "체코", age: 26, rating: 76 },
            { name: "로만 야렘추크", position: "FW", country: "우크라이나", age: 31, rating: 75 },
            { name: "한스 하테부르", position: "DF", country: "네덜란드", age: 32, rating: 75 },
            { name: "클린톤 마타", position: "DF", country: "앙골라", age: 34, rating: 78 },
            { name: "레미 데캉", position: "GK", country: "프랑스", age: 30, rating: 72 },
        ],
        description: "프랑스 축구의 명문 리옹의 영광 재건을 위한 도전"
    },
};

// 외부 리그 자유계약 선수 풀
const freeAgentPool = [
    { name: "바르트 페르브뤼헌", position: "GK", country: "네덜란드", rating: 85, age: 22 },
    { name: "디오고 코스타", position: "GK", country: "포르투갈", rating: 86, age: 25 },
    { name: "조던 픽포드", position: "GK", country: "잉글랜드", rating: 83, age: 31 },
    { name: "조규성", position: "FW", country: "대한민국", rating: 80, age: 27 },
    { name: "황희찬", position: "FW", country: "대한민국", rating: 82, age: 29 },
    { name: "이재성", position: "MF", country: "대한민국", rating: 81, age: 33 },
    { name: "설영우", position: "DF", country: "대한민국", rating: 77, age: 27 },
    { name: "이한범", position: "DF", country: "대한민국", rating: 78, age: 23 },
    { name: "윤도영", position: "FW", country: "대한민국", rating: 77, age: 19 },
    { name: "조르조 스칼비니", position: "DF", country: "이탈리아", rating: 85, age: 21 },
    { name: "아담 와튼", position: "MF", country: "잉글랜드", rating: 84, age: 20 },
    { name: "엘리엇 앤더슨", position: "MF", country: "스코틀랜드", rating: 85, age: 23 },
    { name: "히오르히 수다코프", position: "MF", country: "우크라이나", rating: 82, age: 22 },
    { name: "폴 포그바", position: "MF", country: "프랑스", rating: 80, age: 32 },
    { name: "델레 알리", position: "MF", country: "잉글랜드", rating: 79, age: 29 },
    { name: "무사 알 타마리", position: "FW", country: "요르단", rating: 79, age: 28 },
    { name: "아크람 아피프", position: "FW", country: "카타르", rating: 79, age: 29 },
];

// 아이콘 선수 목록 (레전드)
const iconPlayersList = [
    { name: "디에고 마라도나", position: "FW", country: "아르헨티나" },
    { name: "펠레", position: "FW", country: "브라질" },
    { name: "요한 크루이프", position: "MF", country: "네덜란드" },
    { name: "지네딘 지단", position: "MF", country: "프랑스" },
    { name: "프란츠 베켄바워", position: "DF", country: "독일" },
    { name: "호나우두", position: "FW", country: "브라질" },
    { name: "즐라탄 이브라히모비치", position: "FW", country: "스웨덴" },
    { name: "파올로 말디니", position: "DF", country: "이탈리아" },
    { name: "안드레스 이니에스타", position: "MF", country: "스페인" },
    { name: "호나우지뉴", position: "FW", country: "브라질" },
    { name: "티에리 앙리", position: "FW", country: "프랑스" },
    { name: "카카", position: "MF", country: "브라질" },
    { name: "안드레아 피를로", position: "MF", country: "이탈리아" },
    { name: "차범근", position: "FW", country: "대한민국" },
    { name: "박지성", position: "MF", country: "대한민국" },
    { name: "토니 크로스", position: "MF", country: "독일" },
    { name: "호베르투 카를로스", position: "DF", country: "브라질" },
    { name: "프랭크 램파드", position: "MF", country: "잉글랜드" },
    { name: "스티븐 제라드", position: "MF", country: "잉글랜드" },
    { name: "레프 야신", position: "GK", country: "소련" },
    { name: "알프레도 디 스테파노", position: "FW", country: "아르헨티나" },
    { name: "마르코 반 바스텐", position: "FW", country: "네덜란드" },
    { name: "히바우두", position: "FW", country: "브라질" },
    { name: "올리버 칸", position: "GK", country: "독일" },
    { name: "피터 슈마이켈", position: "GK", country: "덴마크" },
];

// 국제대회 참가국
const TOURNAMENT_TEAMS = {
    WORLD_CUP: ['FRA','ENG','ESP','GER','POR','ITA','NED','BEL','CRO','DEN','SUI','AUT','POL','TUR','CZE','SWE',
                 'BRA','ARG','URU','COL','ECU','CHI','PAR','PER',
                 'KOR','JPN','KSA','AUS','IRN','QAT','UZB','IRQ',
                 'MAR','SEN','NGA','EGY','ALG','TUN','CMR','CIV','GHA',
                 'USA','MEX','CAN','CRC','PAN','JAM','NZL'],
    EURO: ['FRA','ENG','ESP','GER','POR','ITA','NED','BEL','CRO','DEN','SUI','AUT','POL','TUR','CZE','SWE',
           'UKR','SCO','HUN','SRB','SVK','SVN','ROU','GRE'],
    ASIAN_CUP: ['KOR','JPN','AUS','IRN','KSA','QAT','UZB','JOR','UAE','OMN','CHN','SYR',
                 'VIE','THA','MAS','IDN','IND','TJK','LBN','PLE','BHR','KUW','PRK','KGZ'],
    COPA_AMERICA: ['BRA','ARG','URU','COL','ECU','CHI','PER','PAR','BOL','VEN'],
    AFCON: ['MAR','SEN','NGA','EGY','ALG','TUN','CMR','CIV','GHA','MLI','RSA','BFA',
            'COD','ANG','GUI','CPV','ZAM','BEN','UGA','TOG','GAB','CGO','LBY','SUD'],
};

// 국가 코드 매핑
const COUNTRY_CODE_MAP = {
    '대한민국': 'KOR', '일본': 'JPN', '호주': 'AUS', '이란': 'IRN', '사우디아라비아': 'KSA',
    '카타르': 'QAT', '우즈베키스탄': 'UZB', '이라크': 'IRQ', '프랑스': 'FRA', '잉글랜드': 'ENG',
    '스페인': 'ESP', '독일': 'GER', '포르투갈': 'POR', '이탈리아': 'ITA', '네덜란드': 'NED',
    '벨기에': 'BEL', '크로아티아': 'CRO', '덴마크': 'DEN', '스위스': 'SUI', '오스트리아': 'AUT',
    '폴란드': 'POL', '튀르키예': 'TUR', '체코': 'CZE', '스웨덴': 'SWE', '우크라이나': 'UKR',
    '스코틀랜드': 'SCO', '헝가리': 'HUN', '세르비아': 'SRB', '브라질': 'BRA', '아르헨티나': 'ARG',
    '우루과이': 'URU', '콜롬비아': 'COL', '에콰도르': 'ECU', '칠레': 'CHI', '파라과이': 'PAR',
    '페루': 'PER', '모로코': 'MAR', '세네갈': 'SEN', '나이지리아': 'NGA', '이집트': 'EGY',
    '알제리': 'ALG', '튀니지': 'TUN', '카메룬': 'CMR', '코트디부아르': 'CIV', '가나': 'GHA',
    '미국': 'USA', '멕시코': 'MEX', '캐나다': 'CAN', '노르웨이': 'NOR', '러시아': 'RUS',
};

// 선수 포지션 한글 매핑
const POSITION_KO = { GK: '골키퍼', DF: '수비수', MF: '미드필더', FW: '공격수' };
